language: go
go:
  - "1.7"
  - "1.8"
  - "1.9"
  - "1.10"

install:
  - go get github.com/Masterminds/glide
  - go get github.com/golang/lint/golint
  - go get github.com/kisielk/errcheck
  - glide install

script:
  - go build
  - go test $(glide nv)
  - errcheck
#  - golint
#  - go vet
